services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
      - certificates:/mosquitto/certificates
    ports:
      - 1883:1883
      - 9001:9001
    stdin_open: true
    tty: true

  volumes:
    certificates:
      external: true
    