services:
  freescout-app:
    image: tbfren/freescout
    container_name: freescout-app
    links:
    - freescout-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    #- ./data:/www/html
    ### Or, if you just want to use Stock Freescout and hold onto persistent files like cache and session use this, one or the other.
    - ./data:/data
    ### If you want to just keep the original source and add additional modules uncomment this line
    #- ./modules:/www/html/Modules
    - ./logs/:/www/logs
    environment:
    - CONTAINER_NAME=freescout-app
    - FREESCOUT_URL=https://freescout.idiot.games
    
    - FREESCOUT_ADMIN_FIRSTNAME=Falk
    - FREESCOUT_ADMIN_LASTNAME="Kühnel"
    - FREESCOUT_ADMIN_EMAIL=falk@makerspacebonn.de
    - FREESCOUT_ADMIN_PASS=Passw0rd
    - FREESCOUT_DB_CONN=mysql
    - FREESCOUT_DB_NAME=freescout-db
    - FREESCOUT_DB_USER=freescout
    - FREESCOUT_DB_PASS=freescout
    - FREESCOUT_DB_HOST=freescout-db
    - FREESCOUT_DEBUG	1
    - FREESCOUT_HTTPS true

    - VIRTUAL_HOST=freescout.idiot.games
    - LETSENCRYPT_HOST=freescout.idiot.games
    restart: always
    networks:
      - freescout
      - webproxy


  freescout-db:
    image: tiredofit/mariadb
    container_name: freescout-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=password
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout

      - CONTAINER_NAME=freescout-db
    restart: always
    networks:
      - freescout

  freescout-db-backup:
    container_name: freescout-db-backup
    image: tiredofit/db-backup
    links:
     - freescout-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - CONTAINER_NAME=freescout-db-backup
      - DB_HOST=freescout-db
      - DB_TYPE=mariadb
      - DB_NAME=freescout
      - DB_USER=freescout
      - DB_PASS=freescout
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    restart: always
    networks:
      - freescout

networks:
  freescout:
  webproxy:
    external: true