services:
  msb-bot:
    image: falkkuehnel/msb-inventory
    container_name: msb-bot
    environment:
      - VIRTUAL_HOST=msb-bot.idiot.games
      - LETSENCRYPT_HOST=msb-bot.idiot.games
    env_file:
      - .env
    networks:
      - webproxy

networks:
  webproxy:
    external: true