services:
  msb-bot:
    image: falkkuehnel/msb-bot
    container_name: msb-bot
    environment:
      - VIRTUAL_HOST=msb-bot.idiot.games
      - LETSENCRYPT_HOST=msb-bot.idiot.games
    env_file:
      - .env
    networks:
      - webproxy
  volumes:
      - type: bind
        source: ./msb.prod.config.json
        target: /usr/src/app/msb.config.json

networks:
  webproxy:
    external: true