services:
  agiletechniken:
    image: devisive/agiletechniken
    container_name: agiletechniken
    environment:
      - VIRTUAL_HOST=agiletechniken.creativepeoplespace.de
      - LETSENCRYPT_HOST=agiletechniken.creativepeoplespace.de
    networks:
      - webproxy
    ports:
      - 80:80

networks:
  webproxy:
    external: true