services:

  db:
    container_name: postgres
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - VIRTUAL_HOST=postgres.idiot.games
      - LETSENCRYPT_HOST=postgres.idiot.games
    env_file:
      - postgres_env
    ports:
      - 5432:5432
    networks:
      - webproxy

volumes:
  postgres_data:

networks:
  webproxy:
    external: true